### PR TITLE
Upgrade to version 2.3.0

### PR DESCRIPTION
**Pull request by mlund**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mlund** [comment]
@conda-forge-admin, please rerender

**Comment by mlund** [comment]
I requested re-rendering, but it failed. Also, re-rendering with `conda smithy -c auto` fails due to 

```
conda_build_config.yaml is ambiguous because it does not fully implement all zipped keys, or specifies a subspace that is not fully implemented
```

It's been almost a year since last update. Do I need to update to match the newer build system? ping @conda-forge/core

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
The error was due to the `zipped_keys` from https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/f6e8a2fb2eb19a98b26474efc1fb89a6bf6bcc17/recipe/conda_build_config.yaml#L132-L135 for Windows.
Instead of https://github.com/conda-forge/faunus-feedstock/pull/8/commits/4ac89b019742ff4e022df6c1db3acc6451f14ee4 we could've also changed the `conda_build_config.yaml` to
```yaml
python:    # [not win]
    - 3.6  # [not win]
    - 3.7  # [not win]
```
but I opted for the `skip: True  # [win or py<36]` line so that this can get Python 3.8 without further changes, when needed. (This is assuming it's compatible with Python 3.8.)

**Pull request merged**
